theme: jekyll-theme-minimal
#minimal_mistakes_skin: "air"
title: [Sanjay Narayanaswamy]
description: [My Personal Page]
github:
  is_project_page: false
  hostname: false
endif: true
twitter_username:     hitwhicks
linkedin_username:    sanjay-narayanaswamy

social-network-links:
  rss: true
  email: "sathyasaisanjay[at]gmail.com"
  twitter: hitwhicks
  linkedin: sanjay-narayanaswamy
  
share-links-active:
  twitter: true
  linkedin: true
