theme: jekyll-theme-minimal
#minimal_mistakes_skin: "default"
title: [Sanjay Narayanaswamy]
description: [My Personal Page]
logo : <img src="https://github.com/hitwhicks/Sanjay-Narayanaswamy/blob/master/%E2%80%A2%20Started%20off%20as%20a%20zygote.png" alt="hi" class="inline"/>
