theme: jekyll-theme-minimal
title: [Sanjay Narayanaswamy]
description: [My Personal Page]
logo: ["https://github.com/hitwhicks/Sanjay-Narayanaswamy/blob/master/%E2%80%A2%20Started%20off%20as%20a%20zygote.png"]
