theme: jekyll-theme-minimal
#minimal_mistakes_skin: "air"
title: [Sanjay Narayanaswamy]
description: [My Personal Page]
github:
  is_project_page: false
  hostname: false
endif: true
author:
  email: "sathyasaisanjay[at]gmail.com"
