theme: jekyll-theme-minimal
#minimal_mistakes_skin: "air"
title: [Sanjay Narayanaswamy]
description: [My Personal Page]
github:
  is_project_page: false
  hostname: false
endif: true
twitter_username:     hitwhicks
linkedin_username:    sanjay-narayanaswamy

{% if site.twitter_username %}
  <li>
    <a href="https://twitter.com/{{ site.twitter_username }}">
      <i class="fa fa-twitter"></i> Twitter
    </a>
  </li>
{% endif %}
{% if site.linkedin_username %}
  <li>
    <a href="https://linkedin.com/in/{{ site.linkedin_username }}">
      <i class="fa fa-linkedin"></i> LinkedIn
    </a>
  </li>
{% endif %}
